# Site settings
title: "Creative Engineering"
description: Personal Webpages


# Files
baseurl:
pagesdir: pages
assets:
  libs: assets/libs
  owner: assets/owner
logo: logo.png
#discus_shortname: MADness
email: bryant.engineering@gmail.com
url: "https://debrant.github.io"
search: true
share: true
comments: true

# Read Time is a calculator tp provide post read-time based on word count. Usage is recommended.
readtime: true

# Specify the average Words per minute. If not defined, 180 will be used
wpm: 200

# Owner/author information
owner:
  name:   Debrant
  avatar: avatar.jpg
  # Use the coder's toolbox at https://coderstoolbox.net/string/#!encoding=xml&action=encode&charset=us_ascii to encode your description into XML string
  description:    My personal Webpages


# Social networking links used in footer. Update and remove as you like.
twitter_username: innovate4fun
facebook_username: nathan.bryant.37
github_username: debrant
instagram_username: nbryant73
linkedin_username: bryantengineering


# Internal nav
nav:
 musings: "root_url/musings/"
 gallery: "root_url/family/"
 about: "root_url/goals/"


# Server
destination:      	 ./_site
port:             	 4000


#dependencies
# Gems
plugins:
  - jekyll-paginate


# Build settings
highlighter:         rouge
markdown:           kramdown
kramdown:
    extensions:
     - Hard_wrap
     - no_intra_emphasis
     - strikethrough
     - fenced_code_blocks
     - autolink
     - tables
     - with_toc_data
     - highlight
     - footnotes
    input:          GFM
sass:
    style:          :compressed
paginate: 5
paginate_path: "/musings/page:num/"
permalink: "/musings/:title/"
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
slugify: "pretty"


# Analytics and webmaster tools stuff goes here
google_analytics:   UA-xxxxxxxx-x
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:
